# Generated by Django 3.2 on 2025-03-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sales_app.products'),
        ),
    ]
