# Generated by Django 3.2 on 2025-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_blog_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
